# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d00a8be609f82763252afec00a718b8d75ac0e29c190c30aaab2a9415c839fad6aec0bb5be5db6c5a56b456c138218965ff158bc9dafe7c9f655ad866f83af3

test:
  secret_key_base: 35f396c8e9de1a3bda0f1e59739daf6be087774dd9ccbd812fb3fedef96a55698acffd14f86319b4d99795456e3f8dc3ac07f1ff93375a66ce02ca6a20ded558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
